# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f165a2410556d8c360ca168f93ffb84360f965bf667f9de332fb734495a48e8200dd78a3bf6b69bf0c1f885b342decf9e32f93073bee4d285237c435012bf7

test:
  secret_key_base: f5a45b7f0a4d81a67708aa425d214409ce6839c51eee1122955423e7859f85060fc8cfd62d820ad57df8905dfbb52134c9a0e61a5cb5a67c8eb5e5b41b6489d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
